package blockdude;

import blockdude.models.LevelModel;
import blockdude.views.LevelView;

import javafx.application.Application;
import javafx.scene.control.ScrollPane;
import javafx.stage.Stage;
import javafx.scene.Scene;

public class MainApp extends Application {

	private Stage primaryStage;
	private ScrollPane levelLayout;
    public int levelOneMatrix[][];

	@Override
	public void start(Stage primaryStage) {
		this.primaryStage = primaryStage;
		this.primaryStage.setTitle("Block Dude");
        
        levelOneMatrix = new int[8][20];
        
        levelOneMatrix[0][0] = 0;
        levelOneMatrix[0][1] = 0;
        levelOneMatrix[0][2] = 0;
        levelOneMatrix[0][3] = 0;
        levelOneMatrix[0][4] = 0;
        levelOneMatrix[0][5] = 0;
        levelOneMatrix[0][6] = 0;
        levelOneMatrix[0][7] = 0;
        levelOneMatrix[0][8] = 0;
        levelOneMatrix[0][9] = 0;
        levelOneMatrix[0][10] = 0;
        levelOneMatrix[0][11] = 0;
        levelOneMatrix[0][12] = 0;
        levelOneMatrix[0][13] = 0;
        levelOneMatrix[0][14] = 0;
        levelOneMatrix[0][15] = 0;
        levelOneMatrix[0][16] = 0;
        levelOneMatrix[0][17] = 0;
        levelOneMatrix[0][18] = 0;
        levelOneMatrix[0][19] = 0;
        levelOneMatrix[1][0] = 1;
        levelOneMatrix[1][1] = 1;
        levelOneMatrix[1][2] = 1;
        levelOneMatrix[1][3] = 1;
        levelOneMatrix[1][4] = 1;
        levelOneMatrix[1][5] = 1;
        levelOneMatrix[1][6] = 1;
        levelOneMatrix[1][7] = 1;
        levelOneMatrix[1][8] = 1;
        levelOneMatrix[1][9] = 1;
        levelOneMatrix[1][10] = 1;
        levelOneMatrix[1][11] = 1;
        levelOneMatrix[1][12] = 1;
        levelOneMatrix[1][13] = 1;
        levelOneMatrix[1][14] = 1;
        levelOneMatrix[1][15] = 1;
        levelOneMatrix[1][16] = 1;
        levelOneMatrix[1][17] = 1;
        levelOneMatrix[1][18] = 1;
        levelOneMatrix[1][19] = 1;
        levelOneMatrix[2][0] = 1;
        levelOneMatrix[2][1] = 3;
        levelOneMatrix[2][2] = 0;
        levelOneMatrix[2][3] = 0;
        levelOneMatrix[2][4] = 1;
        levelOneMatrix[2][5] = 0;
        levelOneMatrix[2][6] = 0;
        levelOneMatrix[2][7] = 0;
        levelOneMatrix[2][8] = 1;
        levelOneMatrix[2][9] = 0;
        levelOneMatrix[2][10] = 2;
        levelOneMatrix[2][11] = 0;
        levelOneMatrix[2][12] = 1;
        levelOneMatrix[2][13] = 0;
        levelOneMatrix[2][14] = 2;
        levelOneMatrix[2][15] = 0;
        levelOneMatrix[2][16] = 4;
        levelOneMatrix[2][17] = 0;
        levelOneMatrix[2][18] = 0;
        levelOneMatrix[2][19] = 1;
        levelOneMatrix[3][0] = 1;
        levelOneMatrix[3][1] = 0;
        levelOneMatrix[3][2] = 0;
        levelOneMatrix[3][3] = 0;
        levelOneMatrix[3][4] = 1;
        levelOneMatrix[3][5] = 0;
        levelOneMatrix[3][6] = 0;
        levelOneMatrix[3][7] = 0;
        levelOneMatrix[3][8] = 0;
        levelOneMatrix[3][9] = 0;
        levelOneMatrix[3][10] = 0;
        levelOneMatrix[3][11] = 0;
        levelOneMatrix[3][12] = 1;
        levelOneMatrix[3][13] = 0;
        levelOneMatrix[3][14] = 0;
        levelOneMatrix[3][15] = 0;
        levelOneMatrix[3][16] = 0;
        levelOneMatrix[3][17] = 0;
        levelOneMatrix[3][18] = 0;
        levelOneMatrix[3][19] = 1;
        levelOneMatrix[4][0] = 1;
        levelOneMatrix[4][1] = 0;
        levelOneMatrix[4][2] = 0;
        levelOneMatrix[4][3] = 0;
        levelOneMatrix[4][4] = 0;
        levelOneMatrix[4][5] = 0;
        levelOneMatrix[4][6] = 0;
        levelOneMatrix[4][7] = 0;
        levelOneMatrix[4][8] = 0;
        levelOneMatrix[4][9] = 0;
        levelOneMatrix[4][10] = 0;
        levelOneMatrix[4][11] = 0;
        levelOneMatrix[4][12] = 0;
        levelOneMatrix[4][13] = 0;
        levelOneMatrix[4][14] = 0;
        levelOneMatrix[4][15] = 0;
        levelOneMatrix[4][16] = 0;
        levelOneMatrix[4][17] = 0;
        levelOneMatrix[4][18] = 0;
        levelOneMatrix[4][19] = 1;
        levelOneMatrix[5][0] = 1;
        levelOneMatrix[5][1] = 0;
        levelOneMatrix[5][2] = 0;
        levelOneMatrix[5][3] = 0;
        levelOneMatrix[5][4] = 0;
        levelOneMatrix[5][5] = 0;
        levelOneMatrix[5][6] = 0;
        levelOneMatrix[5][7] = 0;
        levelOneMatrix[5][8] = 0;
        levelOneMatrix[5][9] = 0;
        levelOneMatrix[5][10] = 0;
        levelOneMatrix[5][11] = 0;
        levelOneMatrix[5][12] = 0;
        levelOneMatrix[5][13] = 0;
        levelOneMatrix[5][14] = 0;
        levelOneMatrix[5][15] = 0;
        levelOneMatrix[5][16] = 0;
        levelOneMatrix[5][17] = 0;
        levelOneMatrix[5][18] = 0;
        levelOneMatrix[5][19] = 1;
        levelOneMatrix[6][0] = 1;
        levelOneMatrix[6][1] = 0;
        levelOneMatrix[6][2] = 0;
        levelOneMatrix[6][3] = 0;
        levelOneMatrix[6][4] = 0;
        levelOneMatrix[6][5] = 0;
        levelOneMatrix[6][6] = 0;
        levelOneMatrix[6][7] = 0;
        levelOneMatrix[6][8] = 0;
        levelOneMatrix[6][9] = 0;
        levelOneMatrix[6][10] = 0;
        levelOneMatrix[6][11] = 0;
        levelOneMatrix[6][12] = 0;
        levelOneMatrix[6][13] = 0;
        levelOneMatrix[6][14] = 0;
        levelOneMatrix[6][15] = 0;
        levelOneMatrix[6][16] = 0;
        levelOneMatrix[6][17] = 0;
        levelOneMatrix[6][18] = 0;
        levelOneMatrix[6][19] = 1;
        levelOneMatrix[7][0] = 1;
        levelOneMatrix[7][1] = 0;
        levelOneMatrix[7][2] = 0;
        levelOneMatrix[7][3] = 0;
        levelOneMatrix[7][4] = 0;
        levelOneMatrix[7][5] = 0;
        levelOneMatrix[7][6] = 0;
        levelOneMatrix[7][7] = 0;
        levelOneMatrix[7][8] = 0;
        levelOneMatrix[7][9] = 0;
        levelOneMatrix[7][10] = 0;
        levelOneMatrix[7][11] = 0;
        levelOneMatrix[7][12] = 0;
        levelOneMatrix[7][13] = 0;
        levelOneMatrix[7][14] = 0;
        levelOneMatrix[7][15] = 0;
        levelOneMatrix[7][16] = 0;
        levelOneMatrix[7][17] = 0;
        levelOneMatrix[7][18] = 0;
        levelOneMatrix[7][19] = 1;

		LevelModel model = new LevelModel(levelOneMatrix, 0, 0);
		LevelView view = new LevelView(model);

		primaryStage.setScene(new Scene(view));
		primaryStage.show();
	}

	public static void main(String args[]) {
		launch(args);
	}
}
